		<section class="footer_area">
			<div class="col-md-10 col-md-offset-1 footer_txt">
				<p class="pull-left">&copy; 2014, All Right Reserved.</p>
				<p class="pull-right">Designed & Developed By <a target="_blank" href="http://curryhunter.com">Hasan Fardous Rubel</a></p>
			</div>
		</section>
		

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="../vendor/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="../vendor/js/bootstrap.min.js"></script>
		<script src="../vendor/js/jquery.blueimp-gallery.min.js"></script>
		<script src="../vendor/js/bootstrap-image-gallery.min.js"></script>
        <script src="../vendor/js/plugins.js"></script>
        <script src="../vendor/js/main.js"></script>
    </body>
</html>