<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Your title here</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png" />
		<link rel="stylesheet" href="css/blueimp-gallery.min.css">
		<link rel="stylesheet" href="css/bootstrap-image-gallery.min.css">
		<link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="css/slicknav.css">
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="style.css">
        <link rel="stylesheet" href="responsive.css">
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>
		
		<!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        
		<header class="header_area">
			<div class="container header">
				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 logo">
						<a href="index.html"><i class="fa fa-beer"></i> Curry Hunter</a>
						<span class="show phn_lg"><i class="fa fa-phone"></i> 0000 0000 0000</span>
					</div>
					<div class="col-lg-7 col-md-7 col-sm-9 col-xs-8 mainmenu">
						<ul id="nav">
							<li><a class="active" href="index.html">Home</a></li>
							<li><a href="reviews.html">Reviews</a>
							<li><a href="videos.html">Videos</a>
							<li><a href="photos.html">Photos</a>
							<li><a href="menus.html">Menus</a>
							<li><a href="offers.html">Offers</a>
						</ul>
					</div>		
					<div class="col-lg-2 col-md-2 col-sm-12 col-xs-6 socials">
						<ul>
							<li><a href=""><i class="fa fa-facebook"></i></a></li>
							<li><a href=""><i class="fa fa-twitter"></i></a></li>
							<li><a href=""><i class="fa fa-youtube"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</header>