<?php include("header.phtml");?>
		
		<section class="slider_area">
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
				<li data-target="#carousel-example-generic" data-slide-to="3"></li>
				<li data-target="#carousel-example-generic" data-slide-to="4"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
				<div class="item active">
				  <img src="img/banner.jpg" alt="banner">
				  <div class="carousel-caption">
					<h2>This is First</h2>
					<p>This is First</p>
				  </div>
				</div>
				<div class="item">
				  <img src="img/banner2.jpg" alt="banner">
				  <div class="carousel-caption">
					<h2>This is Second</h2>
					<p>This is Second</p>
				  </div>
				</div>
				<div class="item">
				  <img src="img/banner3.jpg" alt="banner">
				  <div class="carousel-caption">
					<h2>This is Third</h2>
					<p>This is Third</p>
				  </div>
				</div>
				<div class="item">
				  <img src="img/banner4.jpg" alt="banner">
				  <div class="carousel-caption">
					<h2>This is Fourth</h2>
					<p>This is Fourth</p>
				  </div>
				</div>
				<div class="item">
				  <img src="img/banner5.jpg" alt="banner">
				  <div class="carousel-caption">
					<h2>This is Fifth</h2>
					<p>This is fifth</p>
				  </div>
				</div>
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			  </a>
			</div>
		</section>
		<br /><br />
		<section class="sp_offer_area">
			<div class="container sp_offer">
				<div class="row">
					<div class="">
						<h1 class="text-center">Special Offers</h1>
						<hr /><br /><br />
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
					</div>
				</div>
			</div>		
		</section>		
		<br /><br /><br /><br /><hr />
		<section class="good_area">
			<div class="container good">
				<div class="row">
					<div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-xs-offset-2 col-lg-8 col-md-8 col-sm-8 col-xs-8 text-center">
						<h3>We Are Good</h3>
						<h1><i class="fa fa-quote-left"></i> Our Good Food For You <i class="fa fa-quote-right"></i></h1>
						<p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica.</p>
						<a href="" class="more">About Us</a>
					</div>
				</div>
			</div>		
		</section>
		<hr />
		<section class="health_area">
			<div class="container health">
				<div class="row">
					<div class="col-lg-5 col-md-5 col-sm-5">
						<h1>Fast Food Or Health?<br/>We Give You Both.</h1>
						<hr /><br />
						<p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica.</p>
						<a href="" class="more menu">See The Menu</a>
					</div>
					<div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-6 col-md-6 col-sm-6">
						<div class="row">
							<img src="img/fastfood.png" alt="" class="img-responsive pull-left" />
							<img src="img/fastfood2.png" alt="" class="img-responsive pull-right" />
						</div>
						<div class="row">
							<img src="img/fastfood.png" alt="" class="img-responsive pull-left" />
							<img src="img/fastfood2.png" alt="" class="img-responsive pull-right" />
						</div>
					</div>
				</div>
			</div>		
		</section>
		
		<section class="contact_area">
			<div class="container contact">
				<div class="row">
					<div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-lg-6 col-md-6 col-sm-6">
						<div class="row">
							<div class="contact_info text-center">
								<h2>Contact Us</h2>
								<p>Ruhitpur Purba, Ruhitpur, Keranigonj, Dhaka, Bangladesh.</p>
								<h3>0000 - 000 - 0000</h3>
							</div>
							<br />
							<br />
							<br />
							<br />
							<br />
							<a href="" class="more map_lnk">See Location On Map</a>
						</div>
					</div>
				</div>
			</div>		
		</section>
		
<?php include("footer.phtml");?>