<?php include("header.phtml");?>

		<section class="videos_area">
			<div class="container videos">
				<div class="row">
					<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
						<h2>This is the menus page title</h2>
						<div class="menus_acc">
							<div class="panel-group" id="accordion">
							  <div class="panel panel-primary">
								<div class="panel-heading">
								  <h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion"
										href="#accordionOne" class="show">
									  Collapsible Accordion 1
									</a>
								  </h4>
								</div>
								<div id="accordionOne" class="panel-collapse collapse in">
								  <div class="panel-body">
								   Lorem ipsum dolor sit amet, consectetur adipisicing elit,
									sed do eiusmod tempor incididunt ut labore et dolore magna
									aliqua. Ut enim ad minim veniam, quis nostrud exercitation
									ullamco laboris nisi ut aliquip ex ea commodo consequat
									</div>
								</div>
							  </div>
							  <div class="panel panel-success">
								<div class="panel-heading">
								  <h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion"
									   href="#accordionTwo" class="show">
									  Collapsible Accordion 2
									</a>
								  </h4>
								</div>
								<div id="accordionTwo" class="panel-collapse collapse">
								  <div class="panel-body">
									Change does not roll in on the wheels of inevitability,
									but comes through continuous struggle.
									And so we must straighten our backs and work for
									our freedom. A man can't ride you unless your back is bent.
							  </div>
								</div>
							  </div>
							  <div class="panel panel-warning">
								<div class="panel-heading">
								  <h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion" 
									   href="#accordionThree" class="show">
									  Collapsible Accordion 3
									</a>
								  </h4>
								</div>
								
								<div id="accordionThree" class="panel-collapse collapse">
								  <div class="panel-body">
								  You must take personal responsibility.
									You cannot change the circumstances,
									the seasons, or the wind, but you can change yourself.
									That is something you have charge of.
							  </div>
								</div>
							  </div>
							  <div class="panel panel-primary">
								<div class="panel-heading">
								  <h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion" 
									   href="#accordionFour" class="show">
									  Collapsible Accordion 4
									</a>
								  </h4>
								</div>
								
								<div id="accordionFour" class="panel-collapse collapse">
								  <div class="panel-body">
								  You must take personal responsibility.
									You cannot change the circumstances,
									the seasons, or the wind, but you can change yourself.
									That is something you have charge of.
							  </div>
								</div>
							  </div>
							  <div class="panel panel-success">
								<div class="panel-heading">
								  <h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion" 
									   href="#accordionFive" class="show">
									  Collapsible Accordion 5
									</a>
								  </h4>
								</div>
								
								<div id="accordionFive" class="panel-collapse collapse">
								  <div class="panel-body">
								  You must take personal responsibility.
									You cannot change the circumstances,
									the seasons, or the wind, but you can change yourself.
									That is something you have charge of.
							  </div>
								</div>
							  </div>
							</div>
						</div>
					</div>
					
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
						<div class="address widget text-muted">
							<h4>Our Address</h4>
							15<br/>
							Sussex Sqaire<br/>
							Brighton<br/>
							East Sussex<br/>
							BN2 5AA<br/>
							GB
						</div>
						
						<div class="fb_sec widget">
							<h4>FACEBOOK LIKE BOX</h4>
                            <div class="facebook-likebox">								
								<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fcurry.hunter.online&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false"></iframe>
                            </div>
						</div>	
					</div>
				</div>	
			</div>
		</section>	
		
		<br /><br />
		<section class="sp_offer_area">
			<div class="container sp_offer">
				<div class="row">
					<div class="">
						<h1 class="text-center">Special Offers</h1>
						<hr /><br /><br />
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
					</div>
				</div>
			</div>		
		</section>		
		<br /><br /><br /><br />
		
<?php include("footer.phtml");?>