<?php include("header.phtml");?>
		
		<section class="videos_area">
			<div class="container videos">
				<div class="row">
					<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
						<h2>This is the default photo page title</h2>
						<h4 class="text-muted">This is the default photo page description</h4>
						<div class="all_videos all_photos clearfix">
							<div id="links">
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner.jpg" title="Banana" data-gallery>
										<img src="img/banner.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner3.jpg" title="Banana" data-gallery>
										<img src="img/banner3.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner.jpg" title="Banana" data-gallery>
										<img src="img/banner.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner3.jpg" title="Banana" data-gallery>
										<img src="img/banner3.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner.jpg" title="Banana" data-gallery>
										<img src="img/banner.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner3.jpg" title="Banana" data-gallery>
										<img src="img/banner3.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner.jpg" title="Banana" data-gallery>
										<img src="img/banner.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner3.jpg" title="Banana" data-gallery>
										<img src="img/banner3.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
								<div class="sng_photo col-lg-4 col-md-4 col-sm-4 col-xs-4">
									<a href="img/banner.jpg" title="Banana" data-gallery>
										<img src="img/banner.jpg" class="img-responsive" alt="Banana">
										<span>This is image caption.</span>
									</a>
								</div>
							</div>
							<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
							<div id="blueimp-gallery" class="blueimp-gallery">
								<!-- The container for the modal slides -->
								<div class="slides"></div>
								<!-- Controls for the borderless lightbox -->
								<h3 class="title"></h3>
								<a class="prev">‹</a>
								<a class="next">›</a>
								<a class="close">×</a>
								<a class="play-pause"></a>
								<ol class="indicator"></ol>
								<!-- The modal dialog, which will be used to wrap the lightbox content -->
								<div class="modal fade">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<button type="button" class="close" aria-hidden="true">&times;</button>
												<h4 class="modal-title"></h4>
											</div>
											<div class="modal-body next"></div>
											<div class="modal-footer">
												<button type="button" class="btn btn-default pull-left prev">
													<i class="glyphicon glyphicon-chevron-left"></i>
													Previous
												</button>
												<button type="button" class="btn btn-primary next">
													Next
													<i class="glyphicon glyphicon-chevron-right"></i>
												</button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
						<div class="address widget text-muted">
							<h4>Our Address</h4>
							15<br/>
							Sussex Sqaire<br/>
							Brighton<br/>
							East Sussex<br/>
							BN2 5AA<br/>
							GB
						</div>
						
						<div class="fb_sec widget">
							<h4>FACEBOOK LIKE BOX</h4>
                            <div class="facebook-likebox">								
								<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fcurry.hunter.online&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false"></iframe>
                            </div>
						</div>	
					</div>
				</div>	
			</div>
		</section>	
		
		<br /><br />
		<section class="sp_offer_area">
			<div class="container sp_offer">
				<div class="row">
					<div class="">
						<h1 class="text-center">Special Offers</h1>
						<hr /><br /><br />
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
					</div>
				</div>
			</div>		
		</section>		
		<br /><br /><br /><br />
		
<?php include("footer.phtml");?>