<?php include("header.phtml");?>
		
		<section class="videos_area">
			<div class="container videos">
				<div class="row">
					<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
						<h2>This is the default video page title</h2>
						<h4 class="text-muted">This is the default video page description</h4>
						<div class="all_videos clearfix">
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/CqoO69DnBsQ" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/p4gdpuh787o" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/wiSm3eLz2cE" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/F0Kw2WU-H1Y" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/0Uhi9K6-a5Q" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/uzoBJPUREhE" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/CqoO69DnBsQ" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/p4gdpuh787o" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
							
							<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 sing_vid">
								<iframe width="100%" height="auto" src="https://www.youtube.com/embed/wiSm3eLz2cE" frameborder="0" allowfullscreen></iframe>
								<p class="text-muted rvw_name"><b>Beautiful Bangladesh</b></p>
							</div>
						</div>
					</div>
					
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
						<div class="address widget text-muted">
							<h4>Our Address</h4>
							15<br/>
							Sussex Sqaire<br/>
							Brighton<br/>
							East Sussex<br/>
							BN2 5AA<br/>
							GB
						</div>
						
						<div class="fb_sec widget">
							<h4>FACEBOOK LIKE BOX</h4>
                            <div class="facebook-likebox">								
								<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fcurry.hunter.online&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false"></iframe>
                            </div>
						</div>	
					</div>
				</div>	
			</div>
		</section>	
		
		<br /><br />
		<section class="sp_offer_area">
			<div class="container sp_offer">
				<div class="row">
					<div class="">
						<h1 class="text-center">Special Offers</h1>
						<hr /><br /><br />
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>    
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
						
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 sng_off_out">
							<div class="sng_off">
								<p class="ttl"><b>4 persons - $80</b></p>   
								<p><small>Starters : 4 Papadams, Chicken Tikka, Meat Samosa, Onion Bhaji, Lamb Chop
								Main Courses : Chicken Tikka, Sag Gosth, Chicken Dansak, King Prawn Bhuna
								Side Dishes : Dall, Mushroom Bhaji
								Sundries : Keema Nan, Garlic Nan, Egg Rice, Garlic & Onion Rice</small></p>
							</div>
						</div>
					</div>
				</div>
			</div>		
		</section>		
		<br /><br /><br /><br />
		
<?php include("footer.phtml");?>